### ISSUE TITLE
Permission denied from cloning project ideas repository 

### ISSUE THREAD

**Issue by rs1856tn** [utk-cs340-spring22/ClassInfo#1]
It is not allowing me to clone the repository. I accepted the invitation to the group so I dont know what the issue is.

<img width="397" alt="Screenshot 2022-02-08 181553" src="https://user-images.githubusercontent.com/81371924/153091705-30251fd2-2537-4949-adda-ada124ca0f6a.png">

**Comment by dlee865** [comment]
Are you able to clone other repos? It looks like an issue with the public key which needs to be configured on your GitHub account. Instructions on how to add an SSH key to your account are here: 
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

Hope that helps, let me know how it goes.
