### ISSUE TITLE
Need to be reinvited to my group

### ISSUE THREAD

**Issue by jmuncy2** [utk-cs340-spring22/ClassInfo#2]
could you please send an invite to my github jmuncy2 so i can join it. I can't see it and when i click on the original link it says invite expired

**Comment by davidalanreid** [comment]
new invite sent

**Comment by jmuncy2** [comment]
I still can't join it

**Comment by jmuncy2** [comment]
I need access to this https://github.com/utk-cs340-spring22/ChocolateThunder

**Comment by dlee865** [comment]
you should have access to the repo now
